title: Stephen Petrides
email: sdpetrides@gmail.com
description: Personal Site
url: "sdpetrides.github.io"
github_username: sdpetrides

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
